<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Status_Code extends CI_Model {

	const SUCCESS = 200;
	const FAILURE = 400;

	const CREATE_ACCOUNT_SUCCESS = 2000; //创建用户成功
	const CREATE_ACCOUNT_FAILURE = 2001; //创建用户失败
	const ACCOUNT_EXISTS = 2002; //创建用户失败

	const ACCOUNT_LOGIN_SUCCESS = 2003; //创建用户失败
	const ACCOUNT_LOGIN_FAILURE = 2004; //创建用户失败


	const ADMIN_LOGIN_SUCCESS = 6000;
	const ADMIN_LOGIN_FAILURE = 6001;

	const CREATE_NEWS_CATEGORY_SUCCESS = 6100;
	const CREATE_NEWS_CATEGORY_FAILURE = 6101;
	const UPDATE_NEWS_CATEGORY_SUCCESS = 6102;
	const UPDATE_NEWS_CATEGORY_FAILURE = 6103;
	const DELETE_NEWS_CATEGORY_SUCCESS = 6104;
	const DELETE_NEWS_CATEGORY_FAILURE = 6105;
	const GET_NEWS_CATEGORY_SUCCESS = 6106;
	const GET_NEWS_CATEGORY_FAILURE = 6107;


	const CREATE_NEWS_SPECIAL_SUCCESS = 6200;
	const CREATE_NEWS_SPECIAL_FAILURE = 6201;
	const UPDATE_NEWS_SPECIAL_SUCCESS = 6202;
	const UPDATE_NEWS_SPECIAL_FAILURE = 6203;
	const DELETE_NEWS_SPECIAL_SUCCESS = 6204;
	const DELETE_NEWS_SPECIAL_FAILURE = 6205;
	const GET_NEWS_SPECIAL_SUCCESS = 6206;
	const GET_NEWS_SPECIAL_FAILURE = 6207;


	const CREATE_NEWS_SUCCESS = 6300;
	const CREATE_NEWS_FAILURE = 6301;
	const UPDATE_NEWS_SUCCESS = 6302;
	const UPDATE_NEWS_FAILURE = 6303;
	const DELETE_NEWS_SUCCESS = 6304;
	const DELETE_NEWS_FAILURE = 6305;
	const GET_NEWS_SUCCESS = 6304;
	const GET_NEWS_FAILURE = 6305;

	const CREATE_TRAINING_CATEGORY_SUCCESS = 6400;
	const CREATE_TRAINING_CATEGORY_FAILURE = 6401;
	const UPDATE_TRAINING_CATEGORY_SUCCESS = 6402;
	const UPDATE_TRAINING_CATEGORY_FAILURE = 6403;
	const DELETE_TRAINING_CATEGORY_SUCCESS = 6404;
	const DELETE_TRAINING_CATEGORY_FAILURE = 6405;
	const GET_TRAINING_CATEGORY_SUCCESS = 6406;
	const GET_TRAINING_CATEGORY_FAILURE = 6407;

	const CREATE_TRAINING_ORG_SUCCESS = 6500;
	const CREATE_TRAINING_ORG_FAILURE = 6501;
	const UPDATE_TRAINING_ORG_SUCCESS = 6502;
	const UPDATE_TRAINING_ORG_FAILURE = 6503;
	const DELETE_TRAINING_ORG_SUCCESS = 6504;
	const DELETE_TRAINING_ORG_FAILURE = 6505;
	const GET_TRAINING_ORG_SUCCESS = 6506;
	const GET_TRAINING_ORG_FAILURE = 6507;

	const CREATE_TRAINING_COURSE_SUCCESS = 6600;
	const CREATE_TRAINING_COURSE_FAILURE = 6601;
	const UPDATE_TRAINING_COURSE_SUCCESS = 6702;
	const UPDATE_TRAINING_COURSE_FAILURE = 6703;
	const DELETE_TRAINING_COURSE_SUCCESS = 6704;
	const DELETE_TRAINING_COURSE_FAILURE = 6705;
	const GET_TRAINING_COURSE_SUCCESS = 6706;
	const GET_TRAINING_COURSE_FAILURE = 6707;

	const CREATE_SERVICES_COMMON_TEL_CATEGORY_SUCCESS = 6800;
	const CREATE_SERVICES_COMMON_TEL_CATEGORY_FAILURE = 6801;
	const UPDATE_SERVICES_COMMON_TEL_CATEGORY_SUCCESS = 6802;
	const UPDATE_SERVICES_COMMON_TEL_CATEGORY_FAILURE = 6803;
	const DELETE_SERVICES_COMMON_TEL_CATEGORY_SUCCESS = 6804;
	const DELETE_SERVICES_COMMON_TEL_CATEGORY_FAILURE = 6805;
	const GET_SERVICES_COMMON_TEL_CATEGORY_SUCCESS = 6806;
	const GET_SERVICES_COMMON_TEL_CATEGORY_FAILURE = 6807;

	const CREATE_SERVICES_COMMON_TEL_SUCCESS = 6810;
	const CREATE_SERVICES_COMMON_TEL_FAILURE = 6811;
	const UPDATE_SERVICES_COMMON_TEL_SUCCESS = 6812;
	const UPDATE_SERVICES_COMMON_TEL_FAILURE = 6813;
	const DELETE_SERVICES_COMMON_TEL_SUCCESS = 6814;
	const DELETE_SERVICES_COMMON_TEL_FAILURE = 6815;
	const GET_SERVICES_COMMON_TEL_SUCCESS = 6816;
	const GET_SERVICES_COMMON_TEL_FAILURE = 6817;

    const GET_SERVICES_BUS_SUCCESS = 6910;
    const GET_SERVICES_BUS_FAILURE = 6911;

    const CREATE_SERVICES_GUIDE_CATEGORY_SUCCESS = 7000;

    const CREATE_SERVICES_GUIDE_CATEGORY_FAILURE = 7001;
    const UPDATE_SERVICES_GUIDE_CATEGORY_SUCCESS = 7002;
    const UPDATE_SERVICES_GUIDE_CATEGORY_FAILURE = 7003;
    const DELETE_SERVICES_GUIDE_CATEGORY_SUCCESS = 7004;
    const DELETE_SERVICES_GUIDE_CATEGORY_FAILURE = 7005;
    const GET_SERVICES_GUIDE_CATEGORY_SUCCESS = 7006;
    const GET_SERVICES_GUIDE_CATEGORY_FAILURE = 7007;


}

/* End of file Status_code.php */
/* Location: ./application/models/Status_code.php */

?>